In [1]:
import numpy as np

arr=np.array([1,2,3,4,5])
res=arr**2
print(res)

[ 1  4  9 16 25]


In [2]:
ans=arr+12
print(ans)

[13 14 15 16 17]


In [3]:
arr1=np.array([23,34,45])
arr2=np.array([12,32,22])
r=arr1+arr2
print(r)

[35 66 67]


In [5]:
a1=np.array([12,13,14])
a2=np.array([[15,16,17],[21,31,41]])
a=a1+a2
print(a)

[[27 29 31]
 [33 44 55]]
