In [1]:
!pip install numpy


In [3]:
import numpy as np

# from python lists
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [ ]:
#np arrray

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [6]:
np.full((4,7),9)

array([[9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9]])

In [7]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.arange(1,101,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [10]:
np.linspace(1,4,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
#Array Properties

In [12]:
arr=np.array([[10,20,30],[89,99,100]])

print("Shape:",arr.shape)
print("size:",arr.size)
print("Dimensions:",arr.ndim)
print("Data Type:",arr.dtype)

Shape: (2, 3)
size: 6
Dimensions: 2
Data Type: int64


In [14]:
#Changing Data Types

arr=np.array([1,2,3],dtype=np.float32)
print(arr)
print(arr.dtype)

arr_int=arr.astype(np.int32)
print(arr_int)

[1. 2. 3.]
float32
[1 2 3]


In [16]:
#Reshaping and Flattening Arrays

arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)


(2, 4)


In [18]:
reshaped=arr.reshape((4,2))

reshaped

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
flat=arr.flatten()
print(flat)

[1 2 3 4 5 6 7 8]
