In [2]:
import numpy as np

arr=np.array([12,13,14,56,78,90])
print(arr)
print(arr[0])
print(arr[4])

[12 13 14 56 78 90]
12
78


In [3]:
print(arr[1:2])
print(arr[:5])
print(arr[2:])

[13]
[12 13 14 56 78]
[14 56 78 90]


In [4]:
print(arr[::4])

[12 78]


In [5]:
s=arr[1:3]
s[0]=23445
print(s)
print(arr)

[23445    14]
[   12 23445    14    56    78    90]


In [10]:
#Fancy Indexing 

ar=np.array([10,20,30,40])
idx=[2,3,0]
print(ar[idx])

[30 40 10]


In [13]:
#Boolean Masking 
a=np.array([34,45,56,67,21,12,43,90,10])
mask=a>=45
print(mask)
a[mask]

[False  True  True  True False False False  True False]


array([45, 56, 67, 90])