In [1]:
import numpy as np

arr=np.array([12,32,34,45,56,67,90])
np.mean(arr)

np.float64(48.0)

In [2]:
np.std(arr)

np.float64(23.742668041192964)

In [3]:
np.var(arr)

np.float64(563.7142857142857)

In [4]:
np.min(arr)

np.int64(12)

In [5]:
np.max(arr)

np.int64(90)

In [6]:
np.sum(arr)

np.int64(336)

In [7]:
np.prod(arr)

np.int64(198393753600)

In [8]:
np.median(arr)

np.float64(45.0)

In [10]:
np.percentile(arr,20)

np.float64(32.4)

In [11]:
np.argmin(arr)

np.int64(0)

In [12]:
np.argmax(arr)

np.int64(6)

In [13]:
np.corrcoef(arr)

np.float64(1.0)

In [14]:
np.unique(arr)

array([12, 32, 34, 45, 56, 67, 90])

In [15]:
np.diff(arr)

array([20,  2, 11, 11, 11, 23])

In [16]:
np.cumsum(arr)

array([ 12,  44,  78, 123, 179, 246, 336])

In [18]:
np.log(arr)

array([2.48490665, 3.4657359 , 3.52636052, 3.80666249, 4.02535169,
       4.20469262, 4.49980967])

In [19]:
np.exp(arr)

array([1.62754791e+05, 7.89629602e+13, 5.83461743e+14, 3.49342711e+19,
       2.09165950e+24, 1.25236317e+29, 1.22040329e+39])