In [3]:
#Axes in a 2D Array

import numpy as np

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[12 15 18]
[ 6 15 24]


In [6]:
print(arr[1,2])

6


In [10]:
print(arr[0:2, 1:3])

[[2 3]
 [5 6]]


In [11]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])
print(arr3D.shape)


(2, 2, 3)


In [12]:
print(arr3D[0,1,2])
print(arr3D[:,0:])

6
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
first_col = arr[:, 0]
print(first_col)

[1 4 7]


In [14]:
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
