In [3]:
#Create a NumPy array with values from 10 to 100 and print its shape
import numpy as np

arr=np.arange(10,101)
print(arr)
print(arr.shape)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]
(91,)


In [4]:
#Compare the time taken to multiply two Python lists vs. two NumPy arrays
import numpy as np
import time

size = 1000000
list1 = list(range(size))
list2 = list(range(size))

arr1 = np.array(list1)
arr2 = np.array(list2)

start=time.time()
res_list=[a*b for a,b in zip(list1,list2)]
end=time.time()
print("List time:",end-start)

start=time.time()
res_arr=arr1*arr2
end=time.time()
print("NumPy time:", end - start)

List time: 0.1304636001586914
NumPy time: 0.006875753402709961


In [5]:
# find the memory size of a NumPy array with 1 million elements.

import numpy as np

arr=np.arange(1000000)

print("Memory size (bytes):", arr.nbytes)

Memory size (bytes): 8000000


In [3]:
import numpy as np
#Create a 3×3 array filled with random numbers and print its shape

b=np.random.rand(3,3)
print(b)
print(b.shape)

[[0.65035674 0.32926931 0.86110382]
 [0.28327274 0.60973221 0.57803748]
 [0.21580592 0.80189468 0.29576509]]
(3, 3)


In [6]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
floatArr=np.array([1.1, 2.2, 3.3])
print(floatArr.astype(np.int32))

[1 2 3]


In [11]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]
d=np.array([1, 2, 3, 4, 5, 6])
i=d[d%2==0]
print(i)

[2 4 6]


In [13]:
#Reshape a 1D array of size 9 into a 3×3 matrix
oneDArr=np.array([1,2,3,4,5,6,7,8,9])
reshaping=oneDArr.reshape(3,3)
print(reshaping)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
#Use boolean masking to filter numbers greater than 50 in an array
e=np.array([23,45,54,32,21,12,67,87,89,9,80,90])
mask=e>50
print(e[mask])

[54 67 87 89 80 90]
