In [ ]:
#NumPy vs. Python Lists



In [3]:
import numpy as np
import time

size=1_000_000
list1=list(range(size))
list2=list(range(size))

start=time.time()
res=[x+y for x,y in zip(list1,list2)]
end=time.time()
print("Python lists add time:",end-start)

arr1=np.array(list1)
arr2=np.array(list2)

strat=time.time()
res=arr1+arr2
end=time.time()

print("NumPy array addition time:", end - start)


Python lists add time: 0.11655211448669434
NumPy array addition time: 0.30734896659851074


In [6]:
# Creating NumPy Arrays
import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)

arr2=np.array([[12,13,14,15],[16,17,18,19]])
print(arr2)

print("Type:",arr1)
print("Shape 2D arr:",arr2)

[1 2 3 4 5]
[[12 13 14 15]
 [16 17 18 19]]
Type: [1 2 3 4 5]
Shape 2D arr: [[12 13 14 15]
 [16 17 18 19]]


In [9]:
# check memory consumption

import sys

list_data=list(range(1000))
numpy_data=np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [12]:
#Squaring Elements
# list_squares=[x**2 for x in list1]
numpy_squares=arr1**2

# print(list_squares)
print(numpy_squares)

[ 1  4  9 16 25]
